apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: my-app
  name: my-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: my-app
    spec:
      containers:
      - image: tomakh/test:my_app
        name: my-app
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /app/target/application.properties
          name: my-app-claim0
          subPath: application.properties
      restartPolicy: Always
      volumes:
      - name: my-app-claim0
        configMap:
          name: my-config


status: {}
